Hw dao9 kostevich
gigbat/jv-dao pull request #7
Opened 2021-01-22 18:15 UTC by gigbat

2021-01-22 18:50 UTC, ivlytvynets approved these changes

2021-01-25 16:46 UTC, Sofasmile requested changes

2021-01-25 16:46 UTC, Sofasmile commented on src/main/java/internet/shop/controllers/drivers/GetMyCurrentCarsController.java
> +        req.getRequestDispatcher("/WEB-INF/views/drivers/cars_by_driver_id.jsp")
we can use cars/get.jsp here

2021-01-25 16:46 UTC, Sofasmile commented on src/main/java/internet/shop/web/filters/AuthenticationFilter.java
> +        if (url.equals("/login") || url.equals("/drivers/create")) {
щоб в майбутньому блок if не розростався краще винести юрлки в сет, який будемо ініціалізовувати в методі  init()
Тоді в блоці if в нас буде єдина умова:  `if(allowedUrls.contains(url))`

2021-01-25 16:46 UTC, Sofasmile commented on src/main/java/internet/shop/web/filters/AuthenticationFilter.java
> +        if (id == null || driverService.get(id) == null) {
https://mate-academy.github.io/jv-program-fulltime/02_jdbc/checklist/09_filters_checklist.html
- 5 paragraph

2021-01-25 16:46 UTC, Sofasmile commented on src/main/java/internet/shop/security/AuthenticationServiceImpl.java
> +        throw new AuthenticationException("Incorrect login or password");
```suggestion
        Optional<Driver> driver = driverService.findByLogin(login);
        if (driver.isPresent() && driver.get().getPassword().equals(password)) {
            return driver.get();
        }
        throw new AuthenticationException("Incorrect login or password");
```

2021-01-25 21:12 UTC, gigbat commented on src/main/java/internet/shop/controllers/drivers/GetMyCurrentCarsController.java
> +        req.getRequestDispatcher("/WEB-INF/views/drivers/cars_by_driver_id.jsp")
done

2021-01-25 21:15 UTC, gigbat commented on src/main/java/internet/shop/web/filters/AuthenticationFilter.java
> +        if (url.equals("/login") || url.equals("/drivers/create")) {
done

2021-01-25 21:18 UTC, gigbat commented on src/main/java/internet/shop/web/filters/AuthenticationFilter.java
> +        if (id == null || driverService.get(id) == null) {
done

2021-01-25 21:21 UTC, gigbat commented on src/main/java/internet/shop/security/AuthenticationServiceImpl.java
> +        throw new AuthenticationException("Incorrect login or password");
done

2021-01-26 07:50 UTC, Sofasmile requested changes

2021-01-26 07:50 UTC, Sofasmile commented on src/main/java/internet/shop/controllers/drivers/GetMyCurrentCarsController.java
> +        req.getRequestDispatcher("/WEB-INF/views/drivers/get.jsp")
тут точно все працює? можливо так:
```suggestion
        req.getRequestDispatcher("/WEB-INF/views/cars/get.jsp")
```

2021-01-26 07:50 UTC, Sofasmile commented on src/main/java/internet/shop/web/filters/AuthenticationFilter.java
>      private DriverService driverService = (DriverService) injector
do we need these fields?

2021-01-26 08:03 UTC, gigbat commented on src/main/java/internet/shop/controllers/drivers/GetMyCurrentCarsController.java
> +        req.getRequestDispatcher("/WEB-INF/views/drivers/get.jsp")
done

2021-01-26 08:05 UTC, gigbat commented on src/main/java/internet/shop/web/filters/AuthenticationFilter.java
>      private DriverService driverService = (DriverService) injector
no, thanks

2021-01-26 09:17 UTC, Sofasmile approved these changes

2021-01-26 09:35 UTC, merged